name: deploy_to_gcs
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - composer/DI/**

env:
  SLACK_USERNAME: DeployBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v3'


      #-- Slack通知 --#
      # 成功
      - name: 'Slack Notification on Success'
        uses: 'rtCamp/action-slack-notify@v2'
        if: ${{ success() }}
        env:
          SLACK_TITLE: 'Deploy / Success'
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: 'デプロイ成功しました:rocket:'

      # 失敗
      - name: 'Slack Notification on Failure'
        uses: 'rtCamp/action-slack-notify@v2'
        if: ${{ failure() }}
        env:
          SLACK_TITLE: 'Deploy / Failure'
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: 'デプロイ失敗しました:cry:'