name: deploy_to_gcs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - composer/DI/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{ vars.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL }}/providers/github'
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'composer/DI'
          destination: 'asia-northeast1-tbk-dap-pro-0148ae88-bucket/dags'

      #-- Teams通知 --#
      # 成功
      - name: 'Teams Notification on Success'
        uses: 'thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b'
        if: ${{ success() }}
          with:
          # WebHook URL of your MS Teams Channel
          teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          # Message to be sent
          message: 'デプロイ完了しました:rocket:'

      # 失敗
      - name: 'Teams Notification on Failure'
        uses: 'thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b'
        if: ${{ failure() }}
          with:
          # WebHook URL of your MS Teams Channel
          teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          # Message to be sent
          message: 'デプロイ失敗しました:cry:'



